version: '3.8'

services:
  financial-chat-assistant:
    build: .
    container_name: financial-rag-engine
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./financial_documents_db:/app/financial_documents_db
      - ./conversations.db:/app/conversations.db
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
    driver: local
  documents_data:
    driver: local
  logs_data:
    driver: local